<?php /** @var \Sparsh\AutoRelatedProducts\Block\ProductList\AutoRelated $block */ ?>
<?php
    $image = 'related_products_list';
    $rule = $block->getRule();
?>
<style>
    .sparsh-auto-related-products-block .products-grid:not(.active-slider) .product-items .product-item{
        max-width:unset!important;
        padding:0px!important;
        min-height:100%!important;
        height:100%!important;
        margin:0px!important;
    }
    .products-grid .items .product-item .product-item-details{
        min-height:150px!important;
    }
   .sparsh-auto-related-products-block ol li .product.photo.product-item-photo{
        aspect-ratio: 1;
        width: 100%;
        display: block;
    }
    .sparsh-auto-related-products-block ol li .product-item-info img {
        width: unset;
        aspect-ratio: unset;
        object-fit: unset;
        height: 100%;
        display: block;
        margin: 0 auto;
    }
  .bay{}
</style>
<?php if ($block->canShowRelatedBlock($rule)): ?>

    <?php

        $items = $block->getProductIds($rule);
    ?>
    <?php if (count($items)): ?>
        <div class="block-content content sparsh-auto-related-products-block">
            <?php if ($block->isPositionPopup($rule)): ?>
                <div class="popup-action" data-opened="true">
                    <div class="close-popup">
                        <span><?= $block->escapeHtml(__('Close')) ?></span>
                    </div>
                    <div class="remove-popup">
                        <span><?= $block->escapeHtml(__('Remove')) ?></span>
                    </div>
                  </div>
            <?php else: ?>
                <h2 class="header-title">
                    <?= $block->escapeHtml(__($rule->getBlockName())) ?>
                </h2>
            <?php endif ?>
            <?php if ($rule->getDisplayLayout() == \Sparsh\AutoRelatedProducts\Ui\Component\Form\DisplayLayouts::ANIMATED_SLIDER): ?>
                <div class="bundles_section">
                    <div class="image-gallery">
                        <div class="image-container owl-carousel owl-theme">
                        <?php foreach ($items as $_item):?>
                            <div class="card">
                                <div class="container">
                                    <img src="/media/catalog/product/<?=$_item->getImage()?>" alt="bundle" class="image">
                                    <p class="header">
                                        <a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= $block->escapeUrl($block->getProductBlock()->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </p>
                                    <?php if ($block->canShowPrice($rule)): ?>
                                        <!-- <p class="price">SAR <span class="quantity">120.75</span></p> -->
                                        <?= /* @noEscape */ $block->getProductBlock()->getProductPrice($_item) ?>
                                    <?php endif ?>
                                    <!-- <p class="old-price">SAR <span class="quantity">120.75</span></p> -->
                                </div>
                            </div>
                        <?php endforeach ?>
                        </div>
                        <div class="owl-theme">
                            <div class="owl-controls">
                                <div class="custom-nav owl-nav disabled">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <script>
                    require(["jquery", "mgsowlcarousel"], function (jQuery) {
                            (function($) {
                              	// Get the current URL
                                var currentUrl = window.location.href;
                                // Check if the URL contains '/ar/'
                                var isRtl = currentUrl.includes('/en/') ?? true;
                                $('.bundles_section .image-container.owl-carousel.owl-theme').owlCarousel({
                                items: 4,
                                loop: true,
                                nav: true,
                                dots: false,
                                autoWidth: false,
                                rtl: !isRtl,
                                navText: [
                                    '<div class="custom-prev"><i class="fa fa-chevron-left" aria-hidden="true"></i></div>',
                                    '<div class="custom-next"><i class="fa fa-chevron-right" aria-hidden="true"></i></div>'
                                ],
                                navContainer: '.bundles_section .image-gallery .custom-nav',
                                responsive : {
                                    0: {
                                        items: 1.5,
                                      	nav: false,
                                      
                                    },
                                 	768: {
                                        items: 4
                                    }
                                  
                                },
                            });
                            })(jQuery);
                        });
                    

                        //bundle section
                        document.querySelectorAll('.card').forEach(card => {
                            card.addEventListener('mouseover', () => {
                                const rotation = getRandomRotation(-5, 5); // Random rotation between -5 and 5 degrees
                                card.style.transform = `scale(1.1) rotate(${rotation}deg)`;
                            });
                            
                            card.addEventListener('mouseout', () => {
                                const rotation = getRandomRotation(-2.5, 2.5); // Random rotation between -2.5 and 2.5 degrees
                                card.style.transform = `scale(1) rotate(${rotation}deg)`;
                                card.style.zIndex = '1';
                            });
                        });
                        
                        function getRandomRotation(min, max) {
                            return Math.random() * (max - min) + min;
                        }
                        
                        const cards = document.querySelectorAll('.card');
                        const cardContainer = document.querySelector('.image-gallery');
                        const observerOptions = {
                            threshold: 0.1
                        };
                        
                        const observer = new IntersectionObserver((entries, observer) => {
                            entries.forEach((entry, index) => {
                                if (entry.isIntersecting) {
                                    setTimeout(() => {
                                        entry.target.classList.add('visible');
                                        observer.unobserve(entry.target);
                                    }, index * 300);
                                }
                            });
                        }, observerOptions);
                        
                        cards.forEach(card => {
                            observer.observe(card);
                        });
                        
                        window.addEventListener('scroll', () => {
                            const containerTop = cardContainer.getBoundingClientRect().top;
                            if (containerTop > window.innerHeight) {
                                cards.forEach(card => {
                                    card.classList.remove('visible');
                                    observer.observe(card);
                                });
                            }
                        });
                </script>
            <?php elseif ($rule->getDisplayLayout() == \Sparsh\AutoRelatedProducts\Ui\Component\Form\DisplayLayouts::MOOD_BOARD): ?>
                <!--Start MOOD_BOARD-->
                <div class="best_sellers_section">
                    <div class="grid-container">
                        <?php
                        $itemcount =0;
                        
                        foreach ($items as $_item){
                            if ($itemcount>8){break;}
                        ?>
                            <div class="grid-item">
                                <a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= $block->escapeUrl($block->getProductBlock()->getProductUrl($_item)) ?>">
                                  <img class="image" src="/media/catalog/product/<?=$_item->getImage()?>" alt="Item 1">
                                </a>
                                <p class="label">
                                    <a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= $block->escapeUrl($block->getProductBlock()->getProductUrl($_item)) ?>">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </p>
                                <p class="price"> 
                                    <?php if ($block->canShowPrice($rule)): ?>
                                    <!-- <p class="price">SAR <span class="quantity">120.75</span></p> -->
                                    <?= /* @noEscape */ $block->getProductBlock()->getProductPrice($_item) ?>
                                    <?php endif ?>
                                </p>
                            </div>
                        <?php $itemcount++;} ?>
                    </div>
                </div>
                <!--End MOOD_BOARD-->
            <?php else: ?>
                <div class="products wrapper <?= $rule->getDisplayLayout() == \Sparsh\AutoRelatedProducts\Ui\Component\Form\DisplayLayouts::GRID && !($block->isPositionPopup($rule)) ? 'grid products-grid' : '' ?>">
                    <div class="products wrapper mgs-products grid products-grid">

                    <ol id="<?= $block->escapeHtml('sparsh-auto-related-products-slider-'.$rule->getRuleId()) ?>" class="products list items product-items <?= $block->isDisplaySlider($rule) ? 'sparsh-auto-related-products-slider' : '' ?>">
                        <?php foreach ($items as $_item):?>
                            <li class="item product product-item">
                                <div class="product-item-info">
                                    <div class="product-top">
                                        <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                        <a href="<?= $block->escapeUrl($block->getProductBlock()->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                                            <img  src="/media/catalog/product/<?=$_item->getImage()?>" />
                                        </a>
                                        <div class="product-item-inner">
                                            <?php if ($block->canShowAddToWishlist($rule) || $block->canShowAddToCart($rule) || $block->canShowAddToCompare($rule)):?>
                                                <div class="product actions product-item-actions">
                                                    <?php if ($block->canShowAddToCart($rule)):?>
                                                        <div class="actions-primary">
                                                            <?php if ($_item->getIsInStock()):?>
                                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)):?>
                                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getProductBlock()->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                    </button>
                                                                <?php else:?>
                                                                    <?php
                                                                    $formKey = $block->getFormKey();
                                                                    $formUrl = $block->getProductBlock()->getAddToCartUrl($_item);
                                                                    $urlHelper = $this->helper(\Magento\Framework\Url\Helper\Data::class);
                                                                    $urlEncoded = $urlHelper->getEncodedUrl($formUrl);
                                                                    $returnURL = $block->getCartReturnUrl($rule);

                                                                    ?>
                                                                    <button
                                                                        type="button"
                                                                        title="Add to Cart"
                                                                        data-product-id="<?= $_item->getEntityId(); ?>"
                                                                        data-url-encoded="<?= $urlEncoded; ?>"
                                                                        data-form-key="<?= $formKey; ?>"
                                                                        data-form-url="<?= $block->escapeUrl($formUrl); ?>"
                                                                        data-form-return-url="<?= $block->escapeUrl($returnURL); ?>"
                                                                        class="action tocart primary autoRelatedProductsAddToCart">
                                                                        <span><?php echo __("Add to Cart"); ?></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            <?php else:?>
                                                                <?php if ($_item->getIsInStock()):?>
                                                                    <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                                <?php else:?>
                                                                    <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                                <?php endif; ?>
                                                            <?php endif; ?>
                                                        </div>
                                                    <?php endif; ?>

                                                    <?php if ($block->canShowAddToWishlist($rule) || $block->canShowAddToCompare($rule)): ?>
                                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                            <?php if ($block->canShowAddToWishlist($rule) && $block->isWishListAllowed()): ?>
                                                                <a href="#"
                                                                class="action towishlist"
                                                                data-post='<?= /* @noEscape */ $block->getWishlistParams($_item) ?>'
                                                                data-action="add-to-wishlist">
                                                                <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                                </a>
                                                                <script type="text/x-magento-init">
                                                                    {
                                                                        "body": {
                                                                            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson($_item) ?>
                                                                        }
                                                                    }
                                                                </script>
                                                            <?php endif ?>
                                                            <?php if ($block->canShowAddToCompare($rule)):?>
                                                                <a href="#"
                                                                class="action tocompare"
                                                                title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                                                aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                                                data-post='<?= /* @noEscape */ $block->getComparePostDataParams($_item, $rule) ?>'
                                                                role="button">
                                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                </a>
                                                            <?php endif ?>
                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="product details product-item-details">
                                        <?php if ($block->isPositionPopup($rule)): ?>
                                            <p><?= $block->escapeHtml($rule->getBlockName()) ?></p>
                                        <?php endif ?>

                                        <strong class="product name product-item-name">
                                            <a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= $block->escapeUrl($block->getProductBlock()->getProductUrl($_item)) ?>">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </strong>
                                        <div class="bt_product_size">
                                            <?php 	
                                        
                                                if($_item->getAttributeText('size')){
                                                    echo __("Size") . " " .$_item->getAttributeText('size');
                                                } 
                                            ?>
                                        </div>
                                        <?php if ($block->canShowPrice($rule)): ?>
                                            <?= /* @noEscape */ $block->getProductBlock()->getProductPrice($_item) ?>
                                        <?php endif ?>
                                        <?php if ($block->canShowReview($rule)): ?>
                                            <?= $block->getProductBlock()->getReviewsSummaryHtml($_item, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW) ?>
                                        <?php endif ?>
                                    
                                    </div>
                                </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                    </div>
                </div>
            <?php endif ?>
        </div>
        <?php endif ?>
<?php endif ?>
<?php if ($block->isPositionPopup($rule)): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "autorelatedPopup": {}
            }
        }
    </script>
<?php else: ?>
    <?php if ($block->isDisplaySlider($rule)): ?>
        <script>
        require([
            'jquery',
            'slick'
        ], function ($) {
            $(document).ready(function () {
                $('<?= $block->escapeHtml('#sparsh-auto-related-products-slider-'.$rule->getRuleId()) ?>').slick({
                        infinite: true,
                        slidesToShow: <?= ($block->isPositionSidebar($rule) ? 1 : ($rule->getRuleId())) ?  4 : 4 ?>,
                        slidesToScroll: 1,
                        dots: true,
                        autoplay: true,
                        arrows: <?= $block->isPositionSidebar($rule) ? "false" : "true" ?>,
                        responsive: [
                        {
                            breakpoint: 1440,
                            settings: {
                                slidesToShow: <?= ($block->isPositionSidebar($rule) ? 1 : ($rule->getRuleId())) ?  4 : 4 ?>,
                                slidesToScroll: 1,
                            }
                        },
                        {
                            breakpoint: 1200,
                            settings: {
                                slidesToShow: <?= $block->isPositionSidebar($rule) ? 1 : 3 ?>,
                                slidesToScroll: 1,
                            }
                        },
                        {
                            breakpoint: 850,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 1,
                            }
                        },
                        {
                            breakpoint: 600,
                            settings: {
                                slidesToShow: 1.3,
                                slidesToScroll: 1,
                                variableWidth: false,
                                infinite: false,    
                            }
                        },
                    ]
                }).on('setPosition', function () {
      $(this).find('.slick-slide').height('auto');
      var slickTrack = $(this).find('.slick-track');
      var slickTrackHeight = $(slickTrack).height();
      $(this).find('.slick-slide').css('height', slickTrackHeight + 'px');
      });
            });
        });

    </script>
    <?php endif ?>
<?php endif ?>
<script>
    require(
        [
            'jquery',
            'uiComponent'
        ],
        function(
            $,
            Component
        ) {

            $(document).on("click",".autoRelatedProductsAddToCart",function(){
                var element = this;
                $(element).html('<span>Processing...</span>');

                $.ajax({
                    url: $(element).attr('data-form-url'),
                    data: {product: $(element).attr('data-product-id'), uenc: $(element).attr('data-url-encoded'), form_key: $(element).attr('data-form-key')},
                    dataType: "json",
                    type: 'post',
                    success: function (response) {
                        $(element).html('<span>Add to Cart</span>');

                        if($(element).attr('data-form-return-url') != 'undefined' && $(element).attr('data-form-return-url') != ''){
                            setTimeout(function(){
                                window.location.href = $(element).attr('data-form-return-url');
                            }, 3000);
                        }
                    }
                });
                return false;
            });

        }
    );
</script>